INSERT INTO Country (Name, Iso3) VALUES ('Afghanistan','AFG');
INSERT INTO Country (Name, Iso3) VALUES ('Albania','ALB');
INSERT INTO Country (Name, Iso3) VALUES ('Algeria','DZA');
INSERT INTO Country (Name, Iso3) VALUES ('American Samoa','ASM');
INSERT INTO Country (Name, Iso3) VALUES ('Andorra','AND');
INSERT INTO Country (Name, Iso3) VALUES ('Angola','AGO');
INSERT INTO Country (Name, Iso3) VALUES ('Anguilla','AIA');
INSERT INTO Country (Name, Iso3) VALUES ('Antarctica',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Antigua and Barbuda','ATG');
INSERT INTO Country (Name, Iso3) VALUES ('Argentina','ARG');
INSERT INTO Country (Name, Iso3) VALUES ('Armenia','ARM');
INSERT INTO Country (Name, Iso3) VALUES ('Aruba','ABW');
INSERT INTO Country (Name, Iso3) VALUES ('Australia','AUS');
INSERT INTO Country (Name, Iso3) VALUES ('Austria','AUT');
INSERT INTO Country (Name, Iso3) VALUES ('Azerbaijan','AZE');
INSERT INTO Country (Name, Iso3) VALUES ('Bahamas','BHS');
INSERT INTO Country (Name, Iso3) VALUES ('Bahrain','BHR');
INSERT INTO Country (Name, Iso3) VALUES ('Bangladesh','BGD');
INSERT INTO Country (Name, Iso3) VALUES ('Barbados','BRB');
INSERT INTO Country (Name, Iso3) VALUES ('Belarus','BLR');
INSERT INTO Country (Name, Iso3) VALUES ('Belgium','BEL');
INSERT INTO Country (Name, Iso3) VALUES ('Belize','BLZ');
INSERT INTO Country (Name, Iso3) VALUES ('Benin','BEN');
INSERT INTO Country (Name, Iso3) VALUES ('Bermuda','BMU');
INSERT INTO Country (Name, Iso3) VALUES ('Bhutan','BTN');
INSERT INTO Country (Name, Iso3) VALUES ('Bolivia','BOL');
INSERT INTO Country (Name, Iso3) VALUES ('Bosnia and Herzegovina','BIH');
INSERT INTO Country (Name, Iso3) VALUES ('Botswana','BWA');
INSERT INTO Country (Name, Iso3) VALUES ('Bouvet Island',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Brazil','BRA');
INSERT INTO Country (Name, Iso3) VALUES ('British Indian Ocean Territory',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Brunei Darussalam','BRN');
INSERT INTO Country (Name, Iso3) VALUES ('Bulgaria','BGR');
INSERT INTO Country (Name, Iso3) VALUES ('Burkina Faso','BFA');
INSERT INTO Country (Name, Iso3) VALUES ('Burundi','BDI');
INSERT INTO Country (Name, Iso3) VALUES ('Cambodia','KHM');
INSERT INTO Country (Name, Iso3) VALUES ('Cameroon','CMR');
INSERT INTO Country (Name, Iso3) VALUES ('Canada','CAN');
INSERT INTO Country (Name, Iso3) VALUES ('Cape Verde','CPV');
INSERT INTO Country (Name, Iso3) VALUES ('Cayman Islands','CYM');
INSERT INTO Country (Name, Iso3) VALUES ('Central African Republic','CAF');
INSERT INTO Country (Name, Iso3) VALUES ('Chad','TCD');
INSERT INTO Country (Name, Iso3) VALUES ('Chile','CHL');
INSERT INTO Country (Name, Iso3) VALUES ('China','CHN');
INSERT INTO Country (Name, Iso3) VALUES ('Christmas Island',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Cocos (Keeling) Islands',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Colombia','COL');
INSERT INTO Country (Name, Iso3) VALUES ('Comoros','COM');
INSERT INTO Country (Name, Iso3) VALUES ('Congo','COG');
INSERT INTO Country (Name, Iso3) VALUES ('Congo, the Democratic Republic of the','COD');
INSERT INTO Country (Name, Iso3) VALUES ('Cook Islands','COK');
INSERT INTO Country (Name, Iso3) VALUES ('Costa Rica','CRI');
INSERT INTO Country (Name, Iso3) VALUES ('Cote D\''Ivoire','CIV');
INSERT INTO Country (Name, Iso3) VALUES ('Croatia','HRV');
INSERT INTO Country (Name, Iso3) VALUES ('Cuba','CUB');
INSERT INTO Country (Name, Iso3) VALUES ('Cyprus','CYP');
INSERT INTO Country (Name, Iso3) VALUES ('Czech Republic','CZE');
INSERT INTO Country (Name, Iso3) VALUES ('Denmark','DNK');
INSERT INTO Country (Name, Iso3) VALUES ('Djibouti','DJI');
INSERT INTO Country (Name, Iso3) VALUES ('Dominica','DMA');
INSERT INTO Country (Name, Iso3) VALUES ('Dominican Republic','DOM');
INSERT INTO Country (Name, Iso3) VALUES ('Ecuador','ECU');
INSERT INTO Country (Name, Iso3) VALUES ('Egypt','EGY');
INSERT INTO Country (Name, Iso3) VALUES ('El Salvador','SLV');
INSERT INTO Country (Name, Iso3) VALUES ('Equatorial Guinea','GNQ');
INSERT INTO Country (Name, Iso3) VALUES ('Eritrea','ERI');
INSERT INTO Country (Name, Iso3) VALUES ('Estonia','EST');
INSERT INTO Country (Name, Iso3) VALUES ('Ethiopia','ETH');
INSERT INTO Country (Name, Iso3) VALUES ('Falkland Islands (Malvinas)','FLK');
INSERT INTO Country (Name, Iso3) VALUES ('Faroe Islands','FRO');
INSERT INTO Country (Name, Iso3) VALUES ('Fiji','FJI');
INSERT INTO Country (Name, Iso3) VALUES ('Finland','FIN');
INSERT INTO Country (Name, Iso3) VALUES ('France','FRA');
INSERT INTO Country (Name, Iso3) VALUES ('French Guiana','GUF');
INSERT INTO Country (Name, Iso3) VALUES ('French Polynesia','PYF');
INSERT INTO Country (Name, Iso3) VALUES ('French Southern Territories',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Gabon','GAB');
INSERT INTO Country (Name, Iso3) VALUES ('Gambia','GMB');
INSERT INTO Country (Name, Iso3) VALUES ('Georgia','GEO');
INSERT INTO Country (Name, Iso3) VALUES ('Germany','DEU');
INSERT INTO Country (Name, Iso3) VALUES ('Ghana','GHA');
INSERT INTO Country (Name, Iso3) VALUES ('Gibraltar','GIB');
INSERT INTO Country (Name, Iso3) VALUES ('Greece','GRC');
INSERT INTO Country (Name, Iso3) VALUES ('Greenland','GRL');
INSERT INTO Country (Name, Iso3) VALUES ('Grenada','GRD');
INSERT INTO Country (Name, Iso3) VALUES ('Guadeloupe','GLP');
INSERT INTO Country (Name, Iso3) VALUES ('Guam','GUM');
INSERT INTO Country (Name, Iso3) VALUES ('Guatemala','GTM');
INSERT INTO Country (Name, Iso3) VALUES ('Guinea','GIN');
INSERT INTO Country (Name, Iso3) VALUES ('Guinea-Bissau','GNB');
INSERT INTO Country (Name, Iso3) VALUES ('Guyana','GUY');
INSERT INTO Country (Name, Iso3) VALUES ('Haiti','HTI');
INSERT INTO Country (Name, Iso3) VALUES ('Heard Island and Mcdonald Islands',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Holy See (Vatican City State)','VAT');
INSERT INTO Country (Name, Iso3) VALUES ('Honduras','HND');
INSERT INTO Country (Name, Iso3) VALUES ('Hong Kong','HKG');
INSERT INTO Country (Name, Iso3) VALUES ('Hungary','HUN');
INSERT INTO Country (Name, Iso3) VALUES ('Iceland','ISL');
INSERT INTO Country (Name, Iso3) VALUES ('India','IND');
INSERT INTO Country (Name, Iso3) VALUES ('Indonesia','IDN');
INSERT INTO Country (Name, Iso3) VALUES ('Iran, Islamic Republic of','IRN');
INSERT INTO Country (Name, Iso3) VALUES ('Iraq','IRQ');
INSERT INTO Country (Name, Iso3) VALUES ('Ireland','IRL');
INSERT INTO Country (Name, Iso3) VALUES ('Israel','ISR');
INSERT INTO Country (Name, Iso3) VALUES ('Italy','ITA');
INSERT INTO Country (Name, Iso3) VALUES ('Jamaica','JAM');
INSERT INTO Country (Name, Iso3) VALUES ('Japan','JPN');
INSERT INTO Country (Name, Iso3) VALUES ('Jordan','JOR');
INSERT INTO Country (Name, Iso3) VALUES ('Kazakhstan','KAZ');
INSERT INTO Country (Name, Iso3) VALUES ('Kenya','KEN');
INSERT INTO Country (Name, Iso3) VALUES ('Kiribati','KIR');
INSERT INTO Country (Name, Iso3) VALUES ('Korea, Democratic People\''s Republic of','PRK');
INSERT INTO Country (Name, Iso3) VALUES ('Korea, Republic of','KOR');
INSERT INTO Country (Name, Iso3) VALUES ('Kuwait','KWT');
INSERT INTO Country (Name, Iso3) VALUES ('Kyrgyzstan','KGZ');
INSERT INTO Country (Name, Iso3) VALUES ('Lao People\''s Democratic Republic','LAO');
INSERT INTO Country (Name, Iso3) VALUES ('Latvia','LVA');
INSERT INTO Country (Name, Iso3) VALUES ('Lebanon','LBN');
INSERT INTO Country (Name, Iso3) VALUES ('Lesotho','LSO');
INSERT INTO Country (Name, Iso3) VALUES ('Liberia','LBR');
INSERT INTO Country (Name, Iso3) VALUES ('Libyan Arab Jamahiriya','LBY');
INSERT INTO Country (Name, Iso3) VALUES ('Liechtenstein','LIE');
INSERT INTO Country (Name, Iso3) VALUES ('Lithuania','LTU');
INSERT INTO Country (Name, Iso3) VALUES ('Luxembourg','LUX');
INSERT INTO Country (Name, Iso3) VALUES ('Macao','MAC');
INSERT INTO Country (Name, Iso3) VALUES ('Macedonia, the Former Yugoslav Republic of','MKD');
INSERT INTO Country (Name, Iso3) VALUES ('Madagascar','MDG');
INSERT INTO Country (Name, Iso3) VALUES ('Malawi','MWI');
INSERT INTO Country (Name, Iso3) VALUES ('Malaysia','MYS');
INSERT INTO Country (Name, Iso3) VALUES ('Maldives','MDV');
INSERT INTO Country (Name, Iso3) VALUES ('Mali','MLI');
INSERT INTO Country (Name, Iso3) VALUES ('Malta','MLT');
INSERT INTO Country (Name, Iso3) VALUES ('Marshall Islands','MHL');
INSERT INTO Country (Name, Iso3) VALUES ('Martinique','MTQ');
INSERT INTO Country (Name, Iso3) VALUES ('Mauritania','MRT');
INSERT INTO Country (Name, Iso3) VALUES ('Mauritius','MUS');
INSERT INTO Country (Name, Iso3) VALUES ('Mayotte',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Mexico','MEX');
INSERT INTO Country (Name, Iso3) VALUES ('Micronesia, Federated States of','FSM');
INSERT INTO Country (Name, Iso3) VALUES ('Moldova, Republic of','MDA');
INSERT INTO Country (Name, Iso3) VALUES ('Monaco','MCO');
INSERT INTO Country (Name, Iso3) VALUES ('Mongolia','MNG');
INSERT INTO Country (Name, Iso3) VALUES ('Montserrat','MSR');
INSERT INTO Country (Name, Iso3) VALUES ('Morocco','MAR');
INSERT INTO Country (Name, Iso3) VALUES ('Mozambique','MOZ');
INSERT INTO Country (Name, Iso3) VALUES ('Myanmar','MMR');
INSERT INTO Country (Name, Iso3) VALUES ('Namibia','NAM');
INSERT INTO Country (Name, Iso3) VALUES ('Nauru','NRU');
INSERT INTO Country (Name, Iso3) VALUES ('Nepal','NPL');
INSERT INTO Country (Name, Iso3) VALUES ('Netherlands','NLD');
INSERT INTO Country (Name, Iso3) VALUES ('Netherlands Antilles','ANT');
INSERT INTO Country (Name, Iso3) VALUES ('New Caledonia','NCL');
INSERT INTO Country (Name, Iso3) VALUES ('New Zealand','NZL');
INSERT INTO Country (Name, Iso3) VALUES ('Nicaragua','NIC');
INSERT INTO Country (Name, Iso3) VALUES ('Niger','NER');
INSERT INTO Country (Name, Iso3) VALUES ('Nigeria','NGA');
INSERT INTO Country (Name, Iso3) VALUES ('Niue','NIU');
INSERT INTO Country (Name, Iso3) VALUES ('Norfolk Island','NFK');
INSERT INTO Country (Name, Iso3) VALUES ('Northern Mariana Islands','MNP');
INSERT INTO Country (Name, Iso3) VALUES ('Norway','NOR');
INSERT INTO Country (Name, Iso3) VALUES ('Oman','OMN');
INSERT INTO Country (Name, Iso3) VALUES ('Pakistan','PAK');
INSERT INTO Country (Name, Iso3) VALUES ('Palau','PLW');
INSERT INTO Country (Name, Iso3) VALUES ('Palestinian Territory, Occupied',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Panama','PAN');
INSERT INTO Country (Name, Iso3) VALUES ('Papua New Guinea','PNG');
INSERT INTO Country (Name, Iso3) VALUES ('Paraguay','PRY');
INSERT INTO Country (Name, Iso3) VALUES ('Peru','PER');
INSERT INTO Country (Name, Iso3) VALUES ('Philippines','PHL');
INSERT INTO Country (Name, Iso3) VALUES ('Pitcairn','PCN');
INSERT INTO Country (Name, Iso3) VALUES ('Poland','POL');
INSERT INTO Country (Name, Iso3) VALUES ('Portugal','PRT');
INSERT INTO Country (Name, Iso3) VALUES ('Puerto Rico','PRI');
INSERT INTO Country (Name, Iso3) VALUES ('Qatar','QAT');
INSERT INTO Country (Name, Iso3) VALUES ('Reunion','REU');
INSERT INTO Country (Name, Iso3) VALUES ('Romania','ROM');
INSERT INTO Country (Name, Iso3) VALUES ('Russian Federation','RUS');
INSERT INTO Country (Name, Iso3) VALUES ('Rwanda','RWA');
INSERT INTO Country (Name, Iso3) VALUES ('Saint Helena','SHN');
INSERT INTO Country (Name, Iso3) VALUES ('Saint Kitts and Nevis','KNA');
INSERT INTO Country (Name, Iso3) VALUES ('Saint Lucia','LCA');
INSERT INTO Country (Name, Iso3) VALUES ('Saint Pierre and Miquelon','SPM');
INSERT INTO Country (Name, Iso3) VALUES ('Saint Vincent and the Grenadines','VCT');
INSERT INTO Country (Name, Iso3) VALUES ('Samoa','WSM');
INSERT INTO Country (Name, Iso3) VALUES ('San Marino','SMR');
INSERT INTO Country (Name, Iso3) VALUES ('Sao Tome and Principe','STP');
INSERT INTO Country (Name, Iso3) VALUES ('Saudi Arabia','SAU');
INSERT INTO Country (Name, Iso3) VALUES ('Senegal','SEN');
INSERT INTO Country (Name, Iso3) VALUES ('Serbia and Montenegro',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Seychelles','SYC');
INSERT INTO Country (Name, Iso3) VALUES ('Sierra Leone','SLE');
INSERT INTO Country (Name, Iso3) VALUES ('Singapore','SGP');
INSERT INTO Country (Name, Iso3) VALUES ('Slovakia','SVK');
INSERT INTO Country (Name, Iso3) VALUES ('Slovenia','SVN');
INSERT INTO Country (Name, Iso3) VALUES ('Solomon Islands','SLB');
INSERT INTO Country (Name, Iso3) VALUES ('Somalia','SOM');
INSERT INTO Country (Name, Iso3) VALUES ('South Africa','ZAF');
INSERT INTO Country (Name, Iso3) VALUES ('South Georgia and the South Sandwich Islands',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Spain','ESP');
INSERT INTO Country (Name, Iso3) VALUES ('Sri Lanka','LKA');
INSERT INTO Country (Name, Iso3) VALUES ('Sudan','SDN');
INSERT INTO Country (Name, Iso3) VALUES ('Suriname','SUR');
INSERT INTO Country (Name, Iso3) VALUES ('Svalbard and Jan Mayen','SJM');
INSERT INTO Country (Name, Iso3) VALUES ('Swaziland','SWZ');
INSERT INTO Country (Name, Iso3) VALUES ('Sweden','SWE');
INSERT INTO Country (Name, Iso3) VALUES ('Switzerland','CHE');
INSERT INTO Country (Name, Iso3) VALUES ('Syrian Arab Republic','SYR');
INSERT INTO Country (Name, Iso3) VALUES ('Taiwan, Province of China','TWN');
INSERT INTO Country (Name, Iso3) VALUES ('Tajikistan','TJK');
INSERT INTO Country (Name, Iso3) VALUES ('Tanzania, United Republic of','TZA');
INSERT INTO Country (Name, Iso3) VALUES ('Thailand','THA');
INSERT INTO Country (Name, Iso3) VALUES ('Timor-Leste',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Togo','TGO');
INSERT INTO Country (Name, Iso3) VALUES ('Tokelau','TKL');
INSERT INTO Country (Name, Iso3) VALUES ('Tonga','TON');
INSERT INTO Country (Name, Iso3) VALUES ('Trinidad and Tobago','TTO');
INSERT INTO Country (Name, Iso3) VALUES ('Tunisia','TUN');
INSERT INTO Country (Name, Iso3) VALUES ('Turkey','TUR');
INSERT INTO Country (Name, Iso3) VALUES ('Turkmenistan','TKM');
INSERT INTO Country (Name, Iso3) VALUES ('Turks and Caicos Islands','TCA');
INSERT INTO Country (Name, Iso3) VALUES ('Tuvalu','TUV');
INSERT INTO Country (Name, Iso3) VALUES ('Uganda','UGA');
INSERT INTO Country (Name, Iso3) VALUES ('Ukraine','UKR');
INSERT INTO Country (Name, Iso3) VALUES ('United Arab Emirates','ARE');
INSERT INTO Country (Name, Iso3) VALUES ('United Kingdom','GBR');
INSERT INTO Country (Name, Iso3) VALUES ('United States','USA');
INSERT INTO Country (Name, Iso3) VALUES ('United States Minor Outlying Islands',NULL);
INSERT INTO Country (Name, Iso3) VALUES ('Uruguay','URY');
INSERT INTO Country (Name, Iso3) VALUES ('Uzbekistan','UZB');
INSERT INTO Country (Name, Iso3) VALUES ('Vanuatu','VUT');
INSERT INTO Country (Name, Iso3) VALUES ('Venezuela','VEN');
INSERT INTO Country (Name, Iso3) VALUES ('Viet Nam','VNM');
INSERT INTO Country (Name, Iso3) VALUES ('Virgin Islands, British','VGB');
INSERT INTO Country (Name, Iso3) VALUES ('Virgin Islands, U.s.','VIR');
INSERT INTO Country (Name, Iso3) VALUES ('Wallis and Futuna','WLF');
INSERT INTO Country (Name, Iso3) VALUES ('Western Sahara','ESH');
INSERT INTO Country (Name, Iso3) VALUES ('Yemen','YEM');
INSERT INTO Country (Name, Iso3) VALUES ('Zambia','ZMB');
INSERT INTO Country (Name, Iso3) VALUES ('Zimbabwe','ZWE');